__merge__: ../../api/comp_control_method.yaml
name: "no_denoising"
label: No Denoising
summary: "negative control by copying train counts"
description: "This method serves as a negative control, where the denoised data is a copy of the unaltered training data. This represents the scoring threshold if denoising was not performed on the data."
info:
  v1:
    path: openproblems/tasks/denoising/methods/baseline.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  variants:
    no_denoising:
  preferred_normalization: counts
resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, midmem, midcpu]
