__merge__: ../../api/comp_control_method.yaml

name: "perfect_denoising"
label: Perfect Denoising
summary: "Positive control by copying the test counts"
description: "This method serves as a positive control, where the test data is copied 1-to-1 to the denoised data. This makes it seem as if the data is perfectly denoised as it will be compared to the test data in the metrics."
info:
  v1:
    path: openproblems/tasks/denoising/methods/baseline.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  variants: 
    perfect_denoising:
  preferred_normalization: counts
resources:
  - type: python_script
    path: script.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, midmem, midcpu]
