__merge__: ../../api/comp_data_processor.yaml
name: "process_dataset"
description: |
  Split data using molecular cross-validation.

  Splits molecules into two (potentially overlapping) groups using a fraction ratio.
  These are output as two separate AnnData objects.
arguments:
  - name: "--method"
    type: "string"
    description: "The process method to assign train/test."
    choices: ["mcv"]
    default: "mcv"
  - name: "--train_frac"
    type: "double"
    description: "The fraction the molecules need to be split to train dataset"
    default: 0.9
  - name: "--seed"
    type: "integer"
    description: "A seed for the subsampling."
    example: 123
  - name: "--n_obs_limit"
    type: "integer"
    description: "The maximum number of cells the dataset may have before subsampling according to `obs.batch`."
    default: 10000
resources:
  - type: python_script
    path: script.py
  - path: helper.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - numpy
          - scipy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu , midtime]
