__merge__: ../../api/comp_method.yaml

name: "alra"
label: ALRA
summary: "ALRA imputes missing values in scRNA-seq data by computing rank-k approximation, thresholding by gene, and rescaling the matrix."
description: |
  Adaptively-thresholded Low Rank Approximation (ALRA). 
  
  ALRA is a method for imputation of missing values in single cell RNA-sequencing data, 
  described in the preprint, "Zero-preserving imputation of scRNA-seq data using low-rank approximation" 
  available [here](https://www.biorxiv.org/content/early/2018/08/22/397588). Given a 
  scRNA-seq expression matrix, ALRA first computes its rank-k approximation using randomized SVD. 
  Next, each row (gene) is thresholded by the magnitude of the most negative value of that gene. 
  Finally, the matrix is rescaled.
references:
  doi: 10.1101/397588
links:
  documentation: https://github.com/KlugerLab/ALRA/blob/master/README.md
  repository: https://github.com/KlugerLab/ALRA
info:
  v1:
    path: openproblems/tasks/denoising/methods/alra.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  variants: 
    alra:
  preferred_normalization: counts
arguments:
  - name: "--norm"
    type: string
    choices: ["sqrt", "log"]
    default: "log"
    description: Normalization method
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        cran: [ Matrix, rsvd ]
        github: KlugerLab/ALRA
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]
