__merge__: ../../api/comp_method.yaml
name: "dca"
label: DCA
summary: "A deep autoencoder with ZINB loss function to address the dropout effect in count data"
description: |
  "Deep Count Autoencoder

  Removes the dropout effect by taking the count structure, overdispersed nature and sparsity of the data into account 
  using a deep autoencoder with zero-inflated negative binomial (ZINB) loss function."
references:
  doi: 10.1038/s41467-018-07931-2
links:
  documentation: "https://github.com/theislab/dca#readme"
  repository: "https://github.com/theislab/dca"
info:
  v1:
    path: openproblems/tasks/denoising/methods/dca.py
    commit: b3456fd73c04c28516f6df34c57e6e3e8b0dab32
  variants: 
    dca:
  preferred_normalization: counts
arguments:
  - name: "--epochs"
    type: "integer"
    default: 300
    description: "Number of total epochs in training"
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: python:3.9
    setup:
      - type: apt
        packages: procps
      - type: python
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
      - type: python
        packages:
          - anndata~=0.8.0
          - scanpy
          - pyyaml
          - requests
          - jsonschema
          - "git+https://github.com/scottgigante-immunai/dca.git@patch-1"
          - numpy<2
runners:
  - type: executable
  - type: nextflow
    directives: 
      label: [midtime, highmem, highcpu]
